const jovianMoons = [
    "Ganymede",
    "Callisto",
    "Io",
    "Europa",
    "Amalthea",
    "Himalia",
    "Thebe",
    "Elara",
    "Pasiphae",
    "Carme",
    "Metis",
    // "Lysithea",
    // "Sinope",
    // "Ananke",
    // "Leda",
    // "Adrastea",
    // "Callirrhoe",
    // "Themisto",
    // "Praxidike",
    // "Kalyke",
    // "Megaclite",
    // "Iocaste",
    // "Taygete",
    // "Dia",
    // "Harpalyke",
    // "Helike",
    // "Thyone",
    // "Hermippe",
    // "Chaldene",
    // "Isonoe",
    // "Eirene",
    // "Euklade",
    // "Aoede",
    // "Autonoe",
    // "Ersa",
    // "Pandia",
    // "Carpo",
    // "Euanthe",
    // "Eurydome",
    // "Erinome",
    // "Aitne",
    // "Arche",
    // "Hegemone",
    // "Euporie",
    // "Eupheme",
    // "Mneme",
    // "Orthoside",
    // "Thelxinoe",
    // "Philophrosyne",
    // "Pasithee",
    // "Kallichore",
    // "Kale",
    // "Herse",
    // "Sponde",
    // "Cyllene",
    // "Kore",
    // "Valetudo"
];